services:
  caddy:
    image: caddy
    restart: unless-stopped
    environment:
      APP_DOMAIN: localhost:8081
      TERMINAL_DOMAIN: localhost:8082
      TERMINAL_HOST: webssh:3000
      APP_HOST: app:8080
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy:/var/www/html
  app:
    build: .
    environment:
      DB_URL: jdbc:postgresql://db:5432/automania
      DB_USERNAME: postgres
      DB_PASSWORD: 12345678
    depends_on:
      - db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  db:
    image: 'postgres:latest'
    env_file: .sample.env
    ports:
      - '5432:5432'

  webssh:
    image: wettyoss/wetty
    ports:
      - "3001:3000"
    command: "--ssh-host=192.168.0.101 --allow-iframe=true --base=/admin/wetty"

volumes:
  db:
  caddy: