services:
  caddy:
    image: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy:/var/www/html

  app:
    image: renattele/admin95:latest
    environment:
      DB_URL: jdbc:postgresql://db:5432/automania
      DB_USERNAME: postgres
      DB_PASSWORD: 12345678
    depends_on:
      - db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  db:
    image: 'postgres:latest'
    volumes:
      - db:/var/lib/postgresql/data

  webssh:
    image: wettyoss/wetty
    command: "--ssh-host=localhost --allow-iframe=true --base=/admin/wetty"

volumes:
  db:
  caddy: