spring:
  config:
    import: optional:admin.properties
  application:
    name: admin95
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    driver-class-name: ${db.driver}
  jpa:
    database-platform: ${db.jpa-driver}
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
  web:
    resources:
      static-locations: [ classpath:/static/,
                          classpath:/public/,
                          classpath:/resources/,
                          classpath:/META-INF/resources/
      ]
      cache:
        period: 0
  messages:
    basename: messages/messages
  mvc:
    log-request-details: true
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    web: DEBUG
    org.springframework.web.servlet.handler.SimpleUrlHandlerMapping: ERROR
    ru.renattele: DEBUG

server:
  port: 8080
  error:
    path: /error