
### Define variables
@host = http://localhost:8080
@auth_token=eyJhbGiOiJIUzI1NiJ9.eyJuYW1lIjoiYWRtaW4iLCJpZCI6MSwic3ViIjoiYWRtaW4iLCJpYXQiOjE3NDczMDIyODcsImV4cCI6MTc0NzQ0NjI4N30.Hv09DuOY2nHZObVLSu0yjwmk1kHlrGybdeIZbM-yazY

### Check Terminal Access
GET {{host}}/api/auth/check/terminal
Authorization: Bearer {{auth_token}}

### Login
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "510f3ac3-dd08-4a95-870d-171acfe53e13"
}
