@username=admin
@password=510f3ac3-dd08-4a95-870d-171acfe53e13

### Check Terminal Access
GET {{host}}/api/auth/check/terminal
Authorization: Bearer {{auth_token}}

### Login
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}
