@host=http://localhost:8080
@auth_token=eyJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiYWRtaW4iLCJpZCI6MSwic3ViIjoiYWRtaW4iLCJpYXQiOjE3NDczMDIyODcsImV4cCI6MTc0NzQ0NjI4N30.Hv09DuOY2nHZObVLSu0yjwmk1kHlrGybdeIZbM-yazY

GET {{host}}/api/admin/backup
Accept: application/json
Authorization: Bearer {{auth_token}}
